name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/daylongcafe:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/daylongcafe:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Stop, remove old container, pull new image
            docker stop daylongcafe || true
            docker rm daylongcafe || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/daylongcafe:latest
            # Run new container and mount the application-local.yml file as external configuration
            docker run -d -p 8080:8080 --name daylongcafe \
              -v /home/ubuntu/application-local.yml:/config/application-local.yml \
              ${{ secrets.DOCKER_USERNAME }}/daylongcafe:latest
